# Generated by Django 6.0.2 on 2026-03-10 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('looking_for', models.CharField(blank=True, max_length=100)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('smoking', models.BooleanField(default=False)),
                ('drinking', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
